name: Build Qv2ray deps for Android

on:
  push:
  schedule:
      - cron: '0 0 */5 * *'
      
jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, x86, x64, arm]
        package: [grpc, openssl, curl]
      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Update vcpkg
      shell: bash
      run: vcpkg update
    
    - name: Update vcpkg - git
      shell: bash
      run: |
        set +e
        cd $VCPKG_INSTALLATION_ROOT
        git pull --verbose
    
    - name: Create triplet
      shell: bash
      run: |
        ORIGINAL_PATH=$(pwd)
        cd $VCPKG_INSTALLATION_ROOT
        git apply -v $ORIGINAL_PATH/0001_vcpkg_fix_curl_android_build.patch
        sudo mkdir -p ./triplets/community
        echo "
        set(VCPKG_TARGET_ARCHITECTURE ${{ matrix.arch }})
        set(VCPKG_CRT_LINKAGE dynamic)
        set(VCPKG_LIBRARY_LINKAGE dynamic)
        set(VCPKG_CMAKE_SYSTEM_NAME Android)
        " | sudo tee ./triplets/community/${{ matrix.arch }}-android.cmake
        ls -lah ./triplets/community
    
    - name: Install version ${{ matrix.package }} ${{ matrix.arch }}
      run: |
        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
        vcpkg install ${{ matrix.package }}:${{ matrix.arch }}-android
      
    - name: Export installed libraries
      shell: bash
      run: |
        vcpkg export ${{ matrix.package }}:${{ matrix.arch }}-android --output=${{ matrix.arch }} --7zip
        cp $VCPKG_INSTALLATION_ROOT/${{ matrix.arch }}.7z ./
        
    - name: Uploading artifact
      uses: actions/upload-artifact@master
      with:
        name: artifacts-${{ matrix.package }}-${{ matrix.arch }}.zip
        path: ${{ matrix.arch }}.7z
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.arch }}.7z
        asset_name: Qv2ray-deps-${{ matrix.package }}-${{ matrix.arch }}.7z
        tag: release
        overwrite: true
