name: Build Qv2ray deps for Windows

on:
  push:
  schedule:
      - cron: '0 0 */2 * *'
      
jobs:
  build:
    strategy:
      matrix:
        arch: [x86-windows, x64-windows]
      fail-fast: false
      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Update vcpkg
      shell: bash
      run: vcpkg update
    
    - name: Update vcpkg - git
      shell: bash
      run: |
        set +e
        cd $VCPKG_INSTALLATION_ROOT
        git pull --verbose
      
    - name: Search for gRPC
      shell: bash
      run: |
        mkdir ./artifacts
        mkdir ./artifacts/${{ matrix.arch }}
        vcpkg search grpc
        vcpkg search grpc > ./artifacts/${{ matrix.arch }}/VERSION
      
    - name: Install version gRPC ${{ matrix.arch }}
      run: vcpkg install grpc:${{ matrix.arch }} pcre2:${{ matrix.arch }} libsodium:${{ matrix.arch }}
      
    - name: Copy installed libraries
      shell: bash
      run: |
        cd artifacts
        cp -rv $VCPKG_INSTALLATION_ROOT/installed/${{ matrix.arch }} ./
        
    - name: Create 7z Release
      uses: DuckSoft/create-7z-action@v1.0
      with:
        pathSource: ./artifacts/${{ matrix.arch }}
        pathTarget: ./artifacts-${{ matrix.arch }}.7z
        
    - name: Uploading artifact
      uses: actions/upload-artifact@master
      with:
        name: artifacts-${{ github.sha }}-${{ matrix.arch }}.zip
        path: ./artifacts-${{ matrix.arch }}.7z
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: artifacts-${{ matrix.arch }}.7z
        asset_name: Qv2ray-deps-${{ matrix.arch }}.7z
        tag: release
        overwrite: true
